# =========================== 服务器配置 ===========================
server:
  port: ${SERVER_PORT:9201}
  ssl:
    enabled: @SSL-ENABLED@
    key-store: classpath:scg-keystore.p12
    key-alias: ${spring.application.name}
    key-store-type: PKCS12
    key-store-password: Zcx@223852//
  http2:
    enabled: @SSL-ENABLED@
  forward-headers-strategy: framework
  shutdown: graceful

# =========================== spring 配置 ===========================
spring:
  threads:
    virtual:
      enabled: true
  application:
    name: @pom.artifactId@
  profiles:
    active: @PROFILE-ACTIVE@
  cloud:
    sentinel:
      filter:
        enabled: true
      eager: true
      transport:
        dashboard: ${SENTINEL-SERVER-ADDRESS}
    loadbalancer:
      cache:
        caffeine:
          spec: initialCapacity=30,expireAfterWrite=30s,maximumSize=4096
        enabled: true
      nacos:
        enabled: true
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*
