name: Build Spring Cloud Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@latest

      - name: Set up JDK 22
        uses: actions/setup-java@latest
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Maven packages
        id: cache-maven-packages
        uses: actions/cache@latest
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@latest
        with:
          name: spring-cloud-jar
          path: target/*.jar
